<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJuwm4Tq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJuwm4Tq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJuwm4Tq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJuwm4Tq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJuwm4Tq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Juwm4Tq',
    'container.build_id' => '025a32c3',
    'container.build_time' => 1631183024,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJuwm4Tq');
