<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ8YOWjp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ8YOWjp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ8YOWjp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ8YOWjp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ8YOWjp\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q8YOWjp',
    'container.build_id' => '782a466f',
    'container.build_time' => 1631099689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ8YOWjp');
