<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQuXSS2S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQuXSS2S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQuXSS2S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQuXSS2S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQuXSS2S\App_KernelDevDebugContainer([
    'container.build_hash' => 'QuXSS2S',
    'container.build_id' => '5a785ad6',
    'container.build_time' => 1631027547,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQuXSS2S');
